$(document).ready(function(){
  $('.owl-carousel').owlCarousel({
    loop:true,
    margin:30,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
        },
        992:{
            items:3,
        },
        1220:{
            items:4,
            loop:false
        }
    }
})
});
